server:
  port: 8585
#  servlet:
#    context-path: /recap

spring:
  sql:
    init:
      mode: always
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:recapdb
#    username: sa
#    password:
#initialization-mode: always